services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fintech_todo
      POSTGRES_PASSWORD: "LJ0YxmdelEJOyTWR_i7_bcldCrgirzlT"
    volumes:
      - fintech_todo_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "JQj-4uSc0mh_AGrGr06Kju6n8aCC_kDU"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fintech_todo_test
      POSTGRES_PASSWORD: "U8IjpwisIK-5CSRUeHvwY-HBrH1cno7h"
    volumes:
      - fintech_todo_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "R9_C6utWjhLpsXGTkwRnpJ6dFuXufl-b"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  fintech_todo_data:
  fintech_todo_test_data:
